//! `docs/src/operators/operators.json` and the feature table in
//! `docs/src/operators/overview.md` are rendered from the operator table
//! (`Engine::operators()`), so the docs and the UI registry (whose test
//! reads `operators.json`) can be checked against what the engine
//! actually ships.
//!
//! The snapshots need every family compiled in. To regenerate both after
//! changing a table row:
//!
//! ```bash
//! UPDATE_OPERATORS_JSON=1 cargo test -p datalogic-rs --all-features --test operators_json_test
//! ```
#![cfg(feature = "all-operators")]

use datalogic_rs::{Engine, OperatorInfo, ScopedArg};

fn quoted(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn render(op: &OperatorInfo) -> String {
    let aliases: Vec<String> = op.aliases.iter().map(|a| quoted(a)).collect();
    let feature = op.feature.map_or("null".to_string(), quoted);
    let max = op.max_args.map_or("null".to_string(), |n| n.to_string());
    let scoped = match op.scoped_arg {
        None => "null".to_string(),
        Some(ScopedArg::Index(i)) => i.to_string(),
        Some(ScopedArg::LastOfMany) => quoted("last"),
        Some(other) => panic!("render {other:?}"),
    };
    format!(
        "  {{\"name\": {}, \"aliases\": [{}], \"family\": {}, \"feature\": {}, \
         \"min_args\": {}, \"max_args\": {}, \"reads_context\": {}, \"effect\": {}, \
         \"cost\": {}, \"scoped_arg\": {}}}",
        quoted(op.name),
        aliases.join(", "),
        quoted(op.family),
        feature,
        op.min_args,
        max,
        op.reads_context,
        quoted(op.effect),
        quoted(op.cost),
        scoped,
    )
}

const REGENERATE: &str = "regenerate with UPDATE_OPERATORS_JSON=1 cargo test -p datalogic-rs \
                          --all-features --test operators_json_test";

const OVERVIEW: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../docs/src/operators/overview.md"
);

fn updating() -> bool {
    std::env::var_os("UPDATE_OPERATORS_JSON").is_some()
}

#[test]
fn operators_json_matches_the_table() {
    let rows: Vec<String> = Engine::new().operators().map(|op| render(&op)).collect();
    let rendered = format!("[\n{}\n]\n", rows.join(",\n"));
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../docs/src/operators/operators.json"
    );
    if updating() {
        std::fs::write(path, &rendered).expect("write operators.json");
        return;
    }
    let on_disk = std::fs::read_to_string(path).unwrap_or_default();
    assert!(
        on_disk == rendered,
        "docs/src/operators/operators.json is stale; {REGENERATE}"
    );
}

/// `name`, or `name`/`alias` for an operator with aliases.
fn spelled(op: &OperatorInfo) -> String {
    std::iter::once(op.name)
        .chain(op.aliases.iter().copied())
        .map(|n| format!("`{n}`"))
        .collect::<Vec<_>>()
        .join("/")
}

/// The "which operators need which Cargo feature" table: one row per
/// feature, in table order, the baseline first.
fn feature_table(ops: &[OperatorInfo]) -> String {
    let mut features: Vec<Option<&str>> = Vec::new();
    for op in ops {
        if !features.contains(&op.feature) {
            features.push(op.feature);
        }
    }
    let mut out = String::from("| Cargo feature | Operators |\n|---------------|-----------|\n");
    for feature in features {
        let names: Vec<String> = ops
            .iter()
            .filter(|op| op.feature == feature)
            .map(spelled)
            .collect();
        let label = feature.map_or("*baseline* (always on)".to_string(), |f| format!("`{f}`"));
        out.push_str(&format!("| {label} | {} |\n", names.join(", ")));
    }
    out
}

/// The generated block in `overview.md`, between its two markers.
#[test]
fn overview_feature_table_matches_the_table() {
    const BEGIN: &str = "<!-- generated by crates/datalogic-rs/tests/operators_json_test.rs from the operator table; do not edit -->\n";
    const END: &str = "<!-- END generated -->\n";
    let ops: Vec<OperatorInfo> = Engine::new().operators().collect();
    let text = std::fs::read_to_string(OVERVIEW).expect("read overview.md");
    let start = text.find(BEGIN).expect("overview.md lost its BEGIN marker") + BEGIN.len();
    let end = start
        + text[start..]
            .find(END)
            .expect("overview.md lost its END marker");
    let rendered = feature_table(&ops);
    if updating() {
        let updated = format!("{}{}{}", &text[..start], rendered, &text[end..]);
        std::fs::write(OVERVIEW, updated).expect("write overview.md");
        return;
    }
    assert!(
        text[start..end] == rendered,
        "the feature table in docs/src/operators/overview.md is stale; {REGENERATE}"
    );
}

/// The hand-written parts of `overview.md` that index the operators: the
/// category table names every operator, and the opening counts add up.
#[test]
fn overview_indexes_every_operator() {
    let ops: Vec<OperatorInfo> = Engine::new().operators().collect();
    let text = std::fs::read_to_string(OVERVIEW).expect("read overview.md");
    let categories = &text[text
        .find("## Operator Categories")
        .expect("category section")
        ..text
            .find("## Which operators need")
            .expect("feature section")];
    let unlisted: Vec<&str> = ops
        .iter()
        .map(|op| op.name)
        .filter(|name| !categories.contains(&format!("`{name}`")))
        .collect();
    assert!(
        unlisted.is_empty(),
        "operators missing from the category table in overview.md: {unlisted:?}"
    );

    let count = |pred: &dyn Fn(&OperatorInfo) -> bool| ops.iter().filter(|op| pred(op)).count();
    let baseline = count(&|op| op.feature.is_none());
    let tensor = count(&|op| op.feature == Some("tensor"));
    let flagd = count(&|op| op.feature == Some("flagd"));
    let others = ops.len() - baseline - tensor - flagd;
    for claim in [
        format!("provides {} built-in operators", ops.len()),
        format!("{baseline} baseline operators"),
        format!("a further {others} canonical operators"),
    ] {
        assert!(
            text.contains(&claim),
            "overview.md should say \"{claim}\" (counted from the operator table)"
        );
    }
    assert_eq!(
        (tensor, flagd),
        (20, 2),
        "update the tensor / flagd counts in overview.md"
    );
}
