/**
 * Generate `src/components/logic-editor/styles/reactflow-base.css` from the
 * installed `@xyflow/react/dist/style.css`.
 *
 * The library bundles React Flow's base styles into its own `styles.css`,
 * so consumers need one CSS import. A hand-copied file drifted from
 * upstream (it lost `touch-action: none` on the pane) and its unscoped
 * `.react-flow*` rules restyled any other React Flow on the host page.
 * The generated copy is upstream verbatim with every selector prefixed by
 * `:where(.logic-editor)`: it applies only inside the editor, and `:where()`
 * adds no specificity, so the editor's own overrides keep winning exactly
 * as before. `@keyframes` blocks are copied unchanged.
 *
 *   node scripts/reactflow-css.mjs          rewrite the file
 *   node scripts/reactflow-css.mjs --check  exit 1 if it is out of date
 *
 * `tests/reactflow-css.test.ts` runs the same check.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const uiRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
export const TARGET = join(uiRoot, 'src/components/logic-editor/styles/reactflow-base.css');
const SCOPE = ':where(.logic-editor)';

/** @returns {{ css: string, version: string }} */
function readUpstream() {
  const require = createRequire(join(uiRoot, 'package.json'));
  const pkgPath = require.resolve('@xyflow/react/package.json');
  const version = JSON.parse(readFileSync(pkgPath, 'utf8')).version;
  const css = readFileSync(join(dirname(pkgPath), 'dist/style.css'), 'utf8');
  return { css, version };
}

/**
 * @param {string} selectorList
 * @returns {string}
 */
function scopeSelectors(selectorList) {
  return selectorList
    .split(',')
    .map((selector) => {
      const trimmed = selector.trim();
      const lead = selector.slice(0, selector.indexOf(trimmed));
      return `${lead}${SCOPE} ${trimmed}`;
    })
    .join(',');
}

/**
 * Prefix every rule's selectors. The upstream file is flat CSS: rules,
 * comments and `@keyframes` blocks, no other at-rules.
 * @param {string} css
 * @returns {string}
 */
export function scopeCss(css) {
  let out = '';
  let i = 0;
  while (i < css.length) {
    // Comments and whitespace between rules pass through.
    const ws = /^\s+/.exec(css.slice(i));
    if (ws) {
      out += ws[0];
      i += ws[0].length;
      continue;
    }
    if (css.startsWith('/*', i)) {
      const end = css.indexOf('*/', i) + 2;
      out += css.slice(i, end);
      i = end;
      continue;
    }
    const open = css.indexOf('{', i);
    if (open < 0) {
      out += css.slice(i);
      break;
    }
    const prelude = css.slice(i, open);
    // Find the matching close brace (keyframes nest one level).
    let depth = 0;
    let close = open;
    for (; close < css.length; close++) {
      if (css[close] === '{') depth++;
      else if (css[close] === '}' && --depth === 0) break;
    }
    const block = css.slice(open, close + 1);
    if (prelude.trim().startsWith('@')) {
      if (!prelude.trim().startsWith('@keyframes')) {
        throw new Error(`reactflow-css: unexpected at-rule "${prelude.trim()}"`);
      }
      out += prelude + block;
    } else {
      out += scopeSelectors(prelude.trimEnd()) + ' ' + block;
    }
    i = close + 1;
  }
  return out;
}

export function generate() {
  const { css, version } = readUpstream();
  const header = `/*
 * React Flow base styles, bundled so the library's styles.css is the only
 * CSS import consumers need.
 *
 * GENERATED by scripts/reactflow-css.mjs from @xyflow/react ${version}
 * dist/style.css: do not edit. Every selector is scoped with
 * ${SCOPE} so these rules never reach another React Flow on the host page;
 * :where() adds no specificity, so the editor's own overrides still win.
 */
`;
  return header + scopeCss(css);
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const next = generate();
  if (process.argv.includes('--check')) {
    if (readFileSync(TARGET, 'utf8') !== next) {
      console.error('reactflow-base.css is out of date: run node scripts/reactflow-css.mjs');
      process.exit(1);
    }
  } else {
    writeFileSync(TARGET, next);
    console.log('wrote', TARGET);
  }
}
