//! The hand-kept declarations of the C ABI must match the generated header.
//!
//! `include/datalogic.h` is generated by cbindgen (and CI checks it is
//! committed up to date). Three wrappers declare the same functions by
//! hand: PHP's FFI header, the JVM's FFM downcall handles and .NET's
//! P/Invoke imports. This test reads all four and fails when a wrapper
//! declares a function the header does not have, when PHP's declaration
//! takes a different number of parameters, or when the header gains a
//! function a wrapper does not declare (except those listed as not
//! wrapped, with the reason). The Go wrapper compiles against a copy of
//! the header itself, so it cannot drift.

use std::collections::{BTreeMap, BTreeSet};

const ROOT: &str = env!("CARGO_MANIFEST_DIR");

/// Functions a wrapper deliberately does not call.
const NOT_WRAPPED: &[(&str, &str, &str)] = &[];

/// Every `datalogic_*` function the C text declares, with its parameter
/// count. Reads declarations (a name followed by `(`, ending in `);`).
fn declarations(text: &str) -> BTreeMap<String, usize> {
    let text: String = text
        .lines()
        .filter(|l| !l.trim_start().starts_with('*') && !l.trim_start().starts_with("/*"))
        .collect::<Vec<_>>()
        .join("\n");
    let mut out = BTreeMap::new();
    let mut rest = text.as_str();
    while let Some(at) = rest.find("datalogic_") {
        let tail = &rest[at..];
        let name: String = tail
            .chars()
            .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
            .collect();
        let after = &tail[name.len()..];
        rest = &tail[name.len()..];
        let after_trim = after.trim_start();
        if !after_trim.starts_with('(') {
            continue;
        }
        // A declaration's parameter list ends in `);`; a typedef'd
        // function pointer or a call does not.
        let Some(close) = after_trim.find(')') else {
            continue;
        };
        if !after_trim[close + 1..].trim_start().starts_with(';') {
            continue;
        }
        let params = after_trim[1..close].trim();
        let count = if params.is_empty() || params == "void" {
            0
        } else {
            params.split(',').count()
        };
        out.insert(name, count);
    }
    out
}

/// Every `datalogic_*` symbol named in a string literal after `marker`.
fn quoted_symbols(text: &str, marker: &str) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    let mut rest = text;
    while let Some(at) = rest.find(marker) {
        rest = &rest[at + marker.len()..];
        let name: String = rest
            .chars()
            .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
            .collect();
        if name.starts_with("datalogic_") {
            out.insert(name);
        }
    }
    out
}

fn read(path: &str) -> String {
    std::fs::read_to_string(format!("{ROOT}/{path}")).unwrap_or_else(|e| panic!("{path}: {e}"))
}

fn header() -> BTreeMap<String, usize> {
    let h = declarations(&read("include/datalogic.h"));
    assert!(
        h.len() > 40,
        "parsed only {} declarations from datalogic.h",
        h.len()
    );
    h
}

fn compare(wrapper: &str, declared: &BTreeSet<String>) {
    let header: BTreeSet<String> = header().into_keys().collect();
    let unknown: Vec<_> = declared.difference(&header).collect();
    assert!(
        unknown.is_empty(),
        "{wrapper} declares functions datalogic.h lacks: {unknown:?}"
    );
    let missing: Vec<_> = header
        .difference(declared)
        .filter(|f| !NOT_WRAPPED.iter().any(|(w, n, _)| *w == wrapper && n == f))
        .collect();
    assert!(
        missing.is_empty(),
        "{wrapper} does not declare: {missing:?}"
    );
}

#[test]
fn php_header_matches() {
    let php = declarations(&read("../php/src/datalogic-ffi.h"));
    let header = header();
    for (name, count) in &php {
        assert_eq!(
            header.get(name),
            Some(count),
            "PHP declares {name} with {count} parameters; datalogic.h has {:?}",
            header.get(name)
        );
    }
    compare("php", &php.into_keys().collect());
}

#[test]
fn jvm_handles_match() {
    let java = read("../jvm/src/main/java/com/goplasmatic/datalogic/internal/DatalogicNative.java");
    compare("jvm", &quoted_symbols(&java, "dh(\""));
}

#[test]
fn dotnet_imports_match() {
    let cs = read("../dotnet/src/Datalogic/Native/NativeMethods.cs");
    compare("dotnet", &quoted_symbols(&cs, "EntryPoint = \""));
}
