[package]
name = "datalogic-web"
version = "3.0.10"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
datalogic-rs = { path = "../../" }
wasm-bindgen = "0.2"
serde_json = "1.0" 