/* SPDX-License-Identifier: Apache-2.0
 *
 * datalogic.h — C ABI for the datalogic-rs JSONLogic engine.
 *
 * Threading & memory model
 * ------------------------
 *  - `datalogic_engine`, `datalogic_rule`, and `datalogic_traced_session`
 *    handles are thread-safe; share across threads freely.
 *  - `datalogic_session` handles are NOT thread-safe; open one per thread.
 *  - Inputs (rule_json, data_json) are caller-owned, NUL-terminated UTF-8.
 *  - Functions returning `char*` transfer ownership — caller must release
 *    via `datalogic_string_free`. NULL is returned on error; query the
 *    thread-local last-error state for details.
 *  - `const char*` returned by `datalogic_last_error_*` and `datalogic_version`
 *    is borrowed; never free. The pointers returned by `datalogic_last_error_*`
 *    remain valid only until the next call on the current thread that
 *    mutates that state.
 */

#ifndef DATALOGIC_H
#define DATALOGIC_H

/* This file is generated by cbindgen. Do not edit by hand — edit the Rust source in bindings/c/src/ and rerun `cargo build -p datalogic-c`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/**
 * Opaque handle wrapping `Arc<datalogic_rs::Engine>`. Send + Sync — share
 * across threads freely. C consumers see this as `struct datalogic_engine`
 * (forward-declared in the generated header).
 */
typedef struct datalogic_engine datalogic_engine;

/**
 * Opaque builder handle. Internally holds an `Option<EngineBuilder>` so
 * each `set_*` / `add_operator` entry point can take the inner by value
 * (the Rust builder consumes `self` on every method) and put it back.
 */
typedef struct datalogic_engine_builder datalogic_engine_builder;

/**
 * Compiled JSONLogic rule. Send + Sync — share one across threads and
 * evaluate in parallel; each `datalogic_rule_evaluate` call creates its
 * own short-lived arena.
 *
 * Holds an `Arc<Engine>` so the engine outlives every rule compiled
 * from it — C consumers can free the engine before the rule and the
 * rule still works (the underlying engine keeps a refcount).
 */
typedef struct datalogic_rule datalogic_rule;

/**
 * Single-threaded session reusing one `bumpalo::Bump` across
 * evaluations. **Not `Sync`** — a session must only ever be used from
 * the thread that created it (the C ABI does not enforce this; consumer
 * languages should).
 *
 * Holds `Arc<Engine>` so the underlying engine outlives the session
 * even if the consumer frees the engine handle first.
 */
typedef struct datalogic_session datalogic_session;

/**
 * Trace-enabled handle over a [`datalogic_rs::Engine`]. Constructed via
 * [`datalogic_engine_traced_session`].
 *
 * Unlike [`crate::session::Session`], this handle carries no per-call
 * arena — `TracedSession` always allocates a fresh `bumpalo::Bump` per
 * run to keep the borrowed-result lifetime tied to the trace. The
 * handle exists for API symmetry (every binding gets `engine ->
 * traced_session -> evaluate`).
 *
 * Holds `Arc<Engine>` so the underlying engine outlives the handle
 * even if the consumer frees the engine handle first.
 */
typedef struct datalogic_traced_session datalogic_traced_session;

/**
 * Callback signature for user-defined operators.
 *
 * * `args_json` — borrowed, NUL-terminated UTF-8 JSON-array string of
 *   pre-evaluated arguments (e.g. `"[1, 2, \"x\"]"`). Do not free.
 * * `user_data` — opaque pointer the caller registered via
 *   [`datalogic_engine_builder_add_operator`].
 * * `error_out` — out-pointer. On error, set `*error_out` to a freshly
 *   `malloc`'d, NUL-terminated UTF-8 message (the binding will call
 *   `free` on it). May be left untouched / `NULL` for a generic error.
 *
 * Returns:
 * - **success**: a freshly `malloc`'d, NUL-terminated UTF-8 JSON string
 *   (e.g. `"42"`, `"\"variant_a\""`, `"{\"a\":1}"`). The binding parses
 *   and then calls `free` on it.
 * - **error**: `NULL`, optionally with `*error_out` filled.
 */
typedef char *(*datalogic_op_callback)(const char *args_json, void *user_data, char **error_out);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return the binding's version as a static, NUL-terminated UTF-8 string.
 *
 * The returned pointer is valid for the program's lifetime — never free it.
 */
 const char *datalogic_version(void);

/**
 * Release a string previously returned by any `datalogic_*` function
 * that documents owned-string return semantics. Safe to call with `NULL`.
 *
 * # Safety
 *
 * `ptr` must either be `NULL` or a pointer previously returned by this
 * library's owned-string path (e.g. [`datalogic_engine_apply`],
 * [`datalogic_rule_evaluate`], [`datalogic_session_evaluate`]). Calling
 * with any other pointer (or twice on the same pointer) is undefined
 * behaviour.
 */
 void datalogic_string_free(char *ptr);

/**
 * `free(3)` from libc. The Rust default allocator on `cdylib` targets
 * is the system allocator (which is libc malloc on Linux/macOS/Windows),
 * so freeing user-supplied `malloc`'d strings via libc `free` is safe
 * across the FFI boundary.
 */
extern void free(void *ptr);

/**
 * Construct a new engine builder. Caller must release the handle via
 * [`datalogic_engine_builder_free`] (no-op after a successful
 * [`datalogic_engine_builder_build`], which consumes the builder).
 */
 datalogic_engine_builder *datalogic_engine_builder_new(void);

/**
 * Free an engine builder handle. Safe with `NULL`. Idempotent after a
 * successful `build()` (which already drops the inner builder; the
 * outer handle still needs freeing).
 *
 * # Safety
 *
 * `builder` must either be `NULL` or a pointer previously returned by
 * [`datalogic_engine_builder_new`] that has not been freed.
 */
 void datalogic_engine_builder_free(datalogic_engine_builder *builder);

/**
 * Toggle templating mode on the builder.
 *
 * # Safety
 *
 * `builder` must be a valid pointer returned by
 * [`datalogic_engine_builder_new`].
 */
 void datalogic_engine_builder_set_templating(datalogic_engine_builder *builder, int32_t enabled);

/**
 * Set the engine's evaluation configuration from a JSON object string.
 *
 * `config_json` is parsed by the core crate's shared config parser
 * ([`EvaluationConfig::from_json_str`]) — the same wire format every
 * binding uses. All keys are optional; an optional `"preset"`
 * (`"default"` | `"safe_arithmetic"` | `"strict"`) selects the starting
 * point and the remaining keys override individual fields on top of it:
 *
 * | Key | Value |
 * |-----|-------|
 * | `preset` | `"default"` \| `"safe_arithmetic"` \| `"strict"` |
 * | `arithmetic_nan_handling` | `"throw_error"` \| `"ignore_value"` \| `"coerce_to_zero"` \| `"return_null"` |
 * | `division_by_zero` | `"return_saturated"` \| `"throw_error"` \| `"return_null"` \| `"return_infinity"` |
 * | `loose_equality_errors` | bool |
 * | `truthy_evaluator` | `"javascript"` \| `"python"` \| `"strict_boolean"` |
 * | `numeric_coercion` | object with bool keys `empty_string_to_zero`, `null_to_zero`, `bool_to_number`, `reject_non_numeric` |
 * | `max_recursion_depth` | integer ≥ 1 |
 *
 * Unknown keys, unknown enum strings, and type mismatches are rejected
 * (tag `"ConfigurationError"`) so typos fail loudly instead of being
 * silently ignored. Each call replaces the builder's entire evaluation
 * config; templating and registered operators are unaffected.
 *
 * Returns `0` on success, `-1` on failure with the thread-local
 * last-error block populated (query
 * [`crate::datalogic_last_error_message`]).
 *
 * # Safety
 *
 * `builder` must be a valid pointer returned by
 * [`datalogic_engine_builder_new`]; `config_json` must be a valid
 * NUL-terminated UTF-8 string.
 */

int32_t datalogic_engine_builder_set_config_json(datalogic_engine_builder *builder,
                                                 const char *config_json);

/**
 * Register a custom operator. The callback is invoked on every match of
 * the operator name during evaluation. See [`DatalogicOpCallback`] for
 * the contract.
 *
 * **Built-ins win** — registering a name that collides with a built-in
 * JSONLogic operator (`+`, `if`, `var`, …) silently does nothing at
 * evaluation time; the built-in dispatches first.
 *
 * # Safety
 *
 * `builder` must be valid; `name` must be NUL-terminated UTF-8;
 * `callback` must be a valid C function pointer (or `NULL` to make this
 * a no-op). `user_data` is opaque to the binding and passed back into
 * every invocation.
 */

int32_t datalogic_engine_builder_add_operator(datalogic_engine_builder *builder,
                                              const char *name,
                                              datalogic_op_callback callback,
                                              void *user_data);

/**
 * Finalise the builder into an [`Engine`]. The builder handle is left
 * in a drained state — [`datalogic_engine_builder_free`] still needs to
 * be called to release the outer allocation.
 *
 * Returns `NULL` if the builder has already been built / is invalid.
 *
 * # Safety
 *
 * `builder` must be a valid pointer returned by
 * [`datalogic_engine_builder_new`].
 */
 datalogic_engine *datalogic_engine_builder_build(datalogic_engine_builder *builder);

/**
 * Construct a new engine. Pass `templating != 0` to enable the engine's
 * templating mode (multi-key objects in compiled rules become
 * output-shaping templates).
 *
 * Returns an owned handle the caller must release via
 * [`datalogic_engine_free`]. Returns `NULL` only if engine construction
 * panics internally (with `"InternalError"` set on the last-error block).
 */
 datalogic_engine *datalogic_engine_new(int32_t templating);

/**
 * Release an engine handle. Safe to call with `NULL`.
 *
 * # Safety
 *
 * `engine` must either be `NULL` or a pointer previously returned by
 * [`datalogic_engine_new`] that has not been freed. Calling with any
 * other pointer (or twice on the same pointer) is undefined behaviour.
 */
 void datalogic_engine_free(datalogic_engine *engine);

/**
 * Compile a JSONLogic rule (`rule_json`, NUL-terminated UTF-8) into a
 * reusable [`Rule`] handle. Returns `NULL` on parse failure — query
 * [`crate::datalogic_last_error_message`] for details.
 *
 * # Safety
 *
 * `engine` must be a valid pointer returned by [`datalogic_engine_new`];
 * `rule_json` must be a valid NUL-terminated UTF-8 string.
 */
 datalogic_rule *datalogic_engine_compile(datalogic_engine *engine, const char *rule_json);

/**
 * One-shot: compile `rule_json` and evaluate against `data_json` in a
 * single call. Returns the result as a freshly-allocated JSON string
 * the caller must release via [`crate::datalogic_string_free`]. Returns
 * `NULL` on failure — query the last-error state for details.
 *
 * For repeated evaluations of the same rule, prefer
 * [`datalogic_engine_compile`] + [`crate::datalogic_rule_evaluate`] to
 * avoid re-parsing on every call.
 *
 * # Safety
 *
 * `engine`, `rule_json`, and `data_json` must all be valid pointers.
 */

char *datalogic_engine_apply(datalogic_engine *engine,
                             const char *rule_json,
                             const char *data_json);

/**
 * Open a hot-loop [`Session`] bound to this engine. The session reuses
 * a single `bumpalo` arena across evaluations and resets it at the
 * start of each call to bound peak memory.
 *
 * Sessions are **not thread-safe** — open one per thread.
 *
 * # Safety
 *
 * `engine` must be a valid pointer returned by [`datalogic_engine_new`].
 */
 datalogic_session *datalogic_engine_session(datalogic_engine *engine);

/**
 * Reset thread-local last-error state. Safe to call when no error is set.
 */
 void datalogic_last_error_clear(void);

/**
 * Return the last error's human-readable message, or `NULL` if no error.
 *
 * The returned pointer is owned by the library; do **not** free. It is
 * valid only until the next call on this thread that mutates the
 * last-error block (any fallible `datalogic_*` call, plus
 * [`datalogic_last_error_clear`]).
 */
 const char *datalogic_last_error_message(void);

/**
 * Return the last error's stable type tag (e.g. `"ParseError"`,
 * `"Thrown"`, `"NaN"`, `"InternalError"`), or `NULL` if no error.
 *
 * Same lifetime caveat as [`datalogic_last_error_message`].
 */
 const char *datalogic_last_error_type(void);

/**
 * Return the outermost failing operator's name (e.g. `"+"`, `"var"`),
 * or `NULL` if the last error didn't originate inside a named operator
 * (or if no error is set).
 */
 const char *datalogic_last_error_operator(void);

/**
 * Return the resolved root-to-leaf error path as a JSON array string
 * (matching the Python binding's `.path` attribute), or `NULL` if not
 * available. Available when the failing call had a compiled `Rule` in
 * scope at the time of failure.
 */
 const char *datalogic_last_error_path_json(void);

/**
 * Release a rule handle. Safe to call with `NULL`.
 *
 * # Safety
 *
 * `rule` must either be `NULL` or a pointer previously returned by
 * [`crate::datalogic_engine_compile`] that has not been freed.
 */
 void datalogic_rule_free(datalogic_rule *rule);

/**
 * Evaluate a compiled rule against `data_json` and return the result
 * as a freshly-allocated JSON string the caller must release via
 * [`crate::datalogic_string_free`]. Returns `NULL` on failure — query
 * the last-error state for details.
 *
 * Uses a short-lived per-call arena. For tight loops, prefer
 * [`crate::datalogic_session_evaluate`] which reuses one arena.
 *
 * # Safety
 *
 * `rule` must be a valid pointer returned by
 * [`crate::datalogic_engine_compile`]; `data_json` must be a valid
 * NUL-terminated UTF-8 string.
 */
 char *datalogic_rule_evaluate(datalogic_rule *rule, const char *data_json);

/**
 * Release a session handle. Safe to call with `NULL`.
 *
 * # Safety
 *
 * `session` must either be `NULL` or a pointer previously returned by
 * [`crate::datalogic_engine_session`] that has not been freed.
 */
 void datalogic_session_free(datalogic_session *session);

/**
 * Evaluate `rule` against `data_json` using the session's reusable
 * arena. The arena is reset at the start of every call so peak memory
 * stays bounded; the previous call's result string has already been
 * materialised by the time we reset.
 *
 * Returns a freshly-allocated JSON string the caller must release via
 * [`crate::datalogic_string_free`]. Returns `NULL` on failure.
 *
 * # Safety
 *
 * `session` and `rule` must be valid pointers; `data_json` must be a
 * valid NUL-terminated UTF-8 string. Must be called from the same
 * thread that created the session.
 */

char *datalogic_session_evaluate(datalogic_session *session,
                                 datalogic_rule *rule,
                                 const char *data_json);

/**
 * Manually reset the session's arena. Optional — every
 * [`datalogic_session_evaluate`] already resets at the start of the call.
 * Exposed mainly for consumers who want to release memory between
 * long pauses between evaluations.
 *
 * # Safety
 *
 * `session` must be a valid pointer or `NULL` (no-op).
 */
 void datalogic_session_reset(datalogic_session *session);

/**
 * Number of bytes currently held by the session's arena (sum across
 * all chunks). Useful for sizing or diagnostics. Returns `0` if
 * `session` is `NULL`.
 *
 * # Safety
 *
 * `session` must be a valid pointer or `NULL`.
 */
 uintptr_t datalogic_session_allocated_bytes(datalogic_session *session);

/**
 * Open a [`TracedSession`] bound to this engine. Every `evaluate` call
 * returns a JSON object carrying the result alongside execution-step and
 * expression-tree metadata.
 *
 * # Safety
 *
 * `engine` must be a valid pointer returned by
 * [`crate::datalogic_engine_new`].
 */
 datalogic_traced_session *datalogic_engine_traced_session(datalogic_engine *engine);

/**
 * Release a traced-session handle. Safe to call with `NULL`.
 *
 * # Safety
 *
 * `session` must either be `NULL` or a pointer previously returned by
 * [`datalogic_engine_traced_session`] that has not been freed.
 */
 void datalogic_traced_session_free(datalogic_traced_session *session);

/**
 * One-shot traced evaluation: compile `rule_json` internally with the
 * optimizer disabled, evaluate against `data_json`, and return the
 * result + trace as a JSON-object string. Engine errors (parse / eval)
 * surface inside the returned JSON's `error` / `structured_error`
 * fields, not as a `NULL` return — `NULL` is reserved for invalid input
 * pointers (null / non-UTF8).
 *
 * Caller releases the returned string via
 * [`crate::datalogic_string_free`].
 *
 * # Safety
 *
 * `session` must be a valid pointer; `rule_json` and `data_json` must be
 * valid NUL-terminated UTF-8 strings.
 */

char *datalogic_traced_session_evaluate(datalogic_traced_session *session,
                                        const char *rule_json,
                                        const char *data_json);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DATALOGIC_H */
